-- TALOD - Fishing goals: what each zone's water asks of your skill, fish
-- bound to the server's hours or seasons, a checklist of notable catches
-- (Nat Pagle's fish, the Stranglethorn Fishing Extravaganza, rare catches)
-- and the Extravaganza's clock. Reference data: FishingData.lua (generated by
-- tools/gen_fishing.py, sources there); your own catches: Fishing.lua's log.
--
-- Zone level (vanilla rule as the CMaNGOS server reconstructs it): a fish is
-- hooked when your skill (lure and gear included) is at least the zone's base
-- and a 1-100 roll is at most skill - base + 5. Below the base every fish gets
-- away; from base + 95 none does. A subzone's own base wins over its zone's.
-- [VERIFY] WoW Forever may use the post-3.1 rule (junk instead of get-aways).
--
-- Clocks: the hours and seasons are the realm's, never your computer's. The
-- realm calendar (C_DateAndTime.GetCurrentCalendarTime) gives the server's
-- date and time; without it, GetGameTime() gives the server's hour and minute
-- and the date is your own shifted by the difference ([VERIFY] on Forever).
--
-- Data in TALODDB.fishing.goals:
--   first     [itemID] = { t, zone, sub, skill, c }: the account's first catch of a goal
--             (c: the character, Store.lua)
--   chars     [character number][itemID] = time: each character's first catch
--   reminded  the date of the last Extravaganza the chat reminder was for

local ADDON_NAME, ns = ...
local S = ns.Secret
local Style = ns.Style
local COLORS, HEX = Style.COLORS, Style.HEX
local Fishing, UI, D = ns.Fishing, ns.FishingUI, ns.FishingData

local Goals = {}
ns.FishingGoals = Goals

local FULL = 95          -- base + this: no fish gets away
local SOON = 60          -- minutes before the Extravaganza it shows on the HUD
local WEEK = 7 * 1440
local WEEKDAYS = { "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday" }
local GROUPS = {
    { key = "pagle", label = "Nat Pagle, Angler Extreme", sub = "Nat Pagle, Dustwallow Marsh: one of each" },
    { key = "stv", label = "Stranglethorn Fishing Extravaganza", sub = "Riggle Bassbait, Booty Bay" },
    { key = "rare", label = "Notable catches", sub = "rare fish, time-of-day and seasonal fish, chests" },
}

local function db() return ns.DB() end

local function Store()
    local f = Fishing.Store()
    if type(f.goals) ~= "table" then f.goals = {} end
    if type(f.goals.first) ~= "table" then f.goals.first = {} end
    return f.goals
end
Goals.Store = Store

---------------------------------------------------------------------------
-- Indexes over the generated data
---------------------------------------------------------------------------
local areaByName, goalById, timedById, whereIndex = {}, {}, {}, {}
for id, a in pairs(D.areas or {}) do areaByName[a[1]] = id end
for _, g in ipairs(D.goals or {}) do
    goalById[g.id] = g
    -- name -> true for a whole zone, or the zone a subzone entry belongs to.
    local w = { zones = {}, subs = {} }
    for _, place in ipairs(g.where or {}) do
        if place[2] then w.subs[place[1]] = place[2] else w.zones[place[1]] = true end
    end
    whereIndex[g.id] = w
end
for _, t in ipairs(D.timed or {}) do timedById[t.id] = t end
Goals.goalById, Goals.timedById = goalById, timedById

local function Info(areaID)
    local a = areaID and D.areas[areaID]
    if not a then return nil end
    return { area = areaID, name = a[1], parent = a[2], base = a[3], min = math.max(1, a[3]), full = a[3] + FULL }
end

-- The zone level of a place: subzone name first (its own base wins), then the
-- map, then the zone name. nil when no data.
function Goals.ZoneLevel(mapID, sub, zone)
    if sub and areaByName[sub] then return Info(areaByName[sub]) end
    if mapID and D.uiMapArea[mapID] then return Info(D.uiMapArea[mapID]) end
    if zone and areaByName[zone] then return Info(areaByName[zone]) end
    return nil
end

function Goals.Here()
    local p = Fishing.Place()
    return Goals.ZoneLevel(p.mapID, p.sub, p.zone), p
end

-- Percent of bites hooked at a skill (nil unknown).
function Goals.Chance(skill, info)
    if not (skill and info) then return nil end
    if skill < info.base then return 0 end
    return math.min(100, skill - info.base + 5)
end

-- The zone line: text, warn, tooltip lines.
function Goals.ZoneText(info, skill)
    if not info then
        return HEX.dim .. "? (no data for this water)|r", false,
            { "Zone fishing level", "No level known for this zone or subzone: fish may get away at any skill." }
    end
    local tip = { "Zone fishing level: " .. info.name .. (info.parent and (" (" .. info.parent .. ")") or ""),
        string.format("From skill %d no fish gets away here.", info.full),
        info.base > 0 and string.format("Below %d every fish gets away.", info.base) or "Any skill can catch fish here.",
        "In between, about skill - " .. info.base .. " + 5 % of bites are hooked (vanilla rule, CMaNGOS data).",
        "Your skill counts your lure and gear." }
    local head = string.format("needs ~%d (you %s)", info.full, skill and tostring(skill) or "?")
    if not skill then
        return head .. HEX.dim .. "  ·  ? hooked|r", false, tip
    end
    if skill >= info.full then
        return head .. HEX.muted .. "  ·  none get away|r", false, tip
    end
    if skill < info.base then
        return HEX.bad .. head .. "  ·  below " .. info.base .. ": all get away|r", true, tip
    end
    return HEX.gold .. head .. "|r" .. HEX.muted .. string.format("  ·  ~%d%% hooked|r", Goals.Chance(skill, info)), true, tip
end

---------------------------------------------------------------------------
-- The server's clock
---------------------------------------------------------------------------
local function Num(v) v = S.Value(v) return type(v) == "number" and v or nil end

-- { hour, min, wday (1 = Sunday), month, day, how } or nil when the game
-- says nothing readable.
function Goals.ServerClock()
    local C = C_DateAndTime
    if C and type(C.GetCurrentCalendarTime) == "function" then
        local t = S.Call(C.GetCurrentCalendarTime)
        if type(t) == "table" then
            local h, m, wd, mo, d = Num(t.hour), Num(t.minute), Num(t.weekday), Num(t.month), Num(t.monthDay)
            if h and m and wd and mo and d and h >= 0 and h < 24 and m >= 0 and m < 60 and wd >= 1 and wd <= 7
                and mo >= 1 and mo <= 12 and d >= 1 and d <= 31 then
                return { hour = math.floor(h), min = math.floor(m), wday = wd, month = mo, day = d, how = "calendar" }
            end
        end
    end
    local h, m = S.CallMulti(2, GetGameTime)
    if type(h) ~= "number" or type(m) ~= "number" or h < 0 or h >= 24 or m < 0 or m >= 60 then return nil end
    h, m = math.floor(h), math.floor(m)
    -- The server's date: yours, moved by the difference between the clocks.
    local now = time()
    local here = date("*t", now)
    local diff = ((h * 60 + m) - (here.hour * 60 + here.min) + 720) % 1440 - 720
    local there = date("*t", now + diff * 60)
    return { hour = h, min = m, wday = there.wday, month = there.month, day = there.day, how = "game" }
end

local function Duration(minutes)
    minutes = math.max(0, math.floor(minutes + 0.5))
    if minutes >= 1440 then return string.format("%d d %d h", math.floor(minutes / 1440), math.floor(minutes % 1440 / 60)) end
    if minutes >= 60 then return string.format("%d h %02d min", math.floor(minutes / 60), minutes % 60) end
    return minutes .. " min"
end
Goals.Duration = Duration

local function ClockText(c)
    if not c then return HEX.dim .. "? (the game gives no server time)|r" end
    return string.format("%s %02d:%02d", WEEKDAYS[c.wday] or "?", c.hour, c.min)
        .. HEX.muted .. (c.how == "calendar" and "  (realm calendar)|r" or "  (server hour, date from yours)|r")
end

-- { on = true, left } or { on = false, untilStart }; nil when the clock is unknown.
function Goals.Extravaganza(clock)
    clock = clock or Goals.ServerClock()
    local e = D.extravaganza
    if not (clock and e) then return nil end
    local now = (clock.wday - 1) * 1440 + clock.hour * 60 + clock.min
    local start = (e.weekday - 1) * 1440 + e.start
    local since = (now - start) % WEEK
    if since < e.length then return { on = true, left = e.length - since } end
    return { on = false, untilStart = (start - now) % WEEK }
end

local function EventWhen()
    local e = D.extravaganza
    return string.format("%ss %02d:%02d-%02d:%02d server time", WEEKDAYS[e.weekday], math.floor(e.start / 60), e.start % 60,
        math.floor((e.start + e.length) / 60), (e.start + e.length) % 60)
end

function Goals.ExtravaganzaText(st)
    if not st then return HEX.dim .. "? (the game gives no server time)|r" end
    if st.on then return HEX.good .. "on now|r  ·  " .. Duration(st.left) .. " left" end
    return "starts in " .. Duration(st.untilStart) .. HEX.muted .. "  (" .. EventWhen() .. ")|r"
end

---------------------------------------------------------------------------
-- Fish of the hour or season
---------------------------------------------------------------------------
local function InHours(h, w)
    if w[1] < w[2] then return h >= w[1] and h < w[2] end
    return h >= w[1] or h < w[2]
end

local function InSeason(md, w)
    if w[1] <= w[2] then return md >= w[1] and md <= w[2] end
    return md >= w[1] or md <= w[2]
end

-- Open now (true / false / nil unknown), and in its best hours.
function Goals.TimedStatus(t, clock)
    if not clock then return nil, nil end
    local open = true
    if t.hours then open = InHours(clock.hour, t.hours) end
    if t.season then open = open and InSeason(clock.month * 100 + clock.day, t.season) end
    local best = t.best and InHours(clock.hour, t.best) or false
    return open, best
end

function Goals.TimedText(t, clock)
    local name = goalById[t.id] and goalById[t.id].name or Fishing.ItemName(t.id)
    local open, best = Goals.TimedStatus(t, clock)
    local now
    if open == nil then now = HEX.dim .. "?|r"
    elseif open then now = HEX.good .. t.open .. "|r" .. (best and (HEX.muted .. " (its best hours)|r") or "")
    else now = HEX.muted .. t.closed .. "|r" end
    return name .. ": " .. t.label .. (t.hours and string.format(" (server %02d-%02d)", t.hours[1], t.hours[2]) or "")
        .. ", now: " .. now, open
end

-- Is an item fished at this place (subzone name, zone name)?
function Goals.FishedAt(id, sub, zone)
    local w = whereIndex[id]
    if not w then return false end
    if zone and w.zones[zone] then return true end
    if sub and (w.zones[sub] or w.subs[sub]) then return true end
    return false
end

-- The zone name of a fishing map (the UiMap's area, else the map's name).
local function MapZone(mapID)
    local info = mapID and D.uiMapArea[mapID] and Info(D.uiMapArea[mapID])
    return info and info.name or (mapID and Fishing.Store().maps[mapID]) or nil
end

---------------------------------------------------------------------------
-- Your catches of the goals
---------------------------------------------------------------------------
-- [itemID] = { n, places = { { mapID, spot, map, n, bands = { [band] = n } } } }
-- Walks every spot and the whole cast log: kept until the fishing data changes.
function Goals.Caught()
    return ns.Data.Memo("fishing:caught", ns.Data.Key("fishing"), Goals.BuildCaught)
end

function Goals.BuildCaught()
    local f = Fishing.Store()
    local out = {}
    local function Entry(id)
        out[id] = out[id] or { n = 0, places = {}, byKey = {} }
        return out[id]
    end
    for mapID, spots in pairs(f.spots) do
        for name, spot in pairs(spots) do
            for band, t in pairs(spot.b or {}) do
                for id, n in pairs(t.it or {}) do
                    if goalById[id] then
                        local e = Entry(id)
                        e.n = e.n + n
                        local key = tostring(mapID) .. "|" .. name
                        local p = e.byKey[key]
                        if not p then
                            p = { mapID = mapID, spot = name, map = f.maps[mapID] or tostring(mapID), n = 0, bands = {} }
                            e.byKey[key] = p
                            e.places[#e.places + 1] = p
                        end
                        p.n = p.n + n
                        p.bands[band] = (p.bands[band] or 0) + n
                    end
                end
            end
        end
    end
    -- Catches without a map position live only in the cast log.
    for _, c in ipairs(Fishing.RecentCasts(#f.casts)) do
        if c.result == "c" and not c.mapID then
            for id, n in pairs(c.items or {}) do
                if goalById[id] then
                    local e = Entry(id)
                    e.n = e.n + n
                    e.unplaced = (e.unplaced or 0) + n
                end
            end
        end
    end
    for _, e in pairs(out) do
        e.byKey = nil
        table.sort(e.places, function(a, b) return a.n > b.n end)
    end
    return out
end

local function BandsText(bands)
    local list = {}
    for b in pairs(bands) do list[#list + 1] = b end
    table.sort(list, function(a, b)
        if type(a) ~= type(b) then return type(a) == "number" end
        return a < b
    end)
    local parts = {}
    for _, b in ipairs(list) do
        parts[#parts + 1] = type(b) == "number" and string.format("%d-%d", b, b + Fishing.BAND - 1) or "skill ?"
    end
    return table.concat(parts, ", ")
end

local function OnLoot(items)
    local store = Store()
    for id, n in pairs(items or {}) do
        local g = goalById[id]
        local me = ns.Store.Me()
        if g and me then
            if type(store.chars) ~= "table" then store.chars = {} end
            store.chars[me] = store.chars[me] or {}
            store.chars[me][id] = store.chars[me][id] or time()
        end
        if g and not store.first[id] then
            local p = Fishing.Place()
            store.first[id] = { t = time(), zone = p.zone, sub = p.sub, skill = Fishing.Effective(), c = ns.Store.Me() }
            if db().fishGoalsAnnounce then ns.Print("fishing goal: your first " .. g.name .. "!") end
        end
    end
end

---------------------------------------------------------------------------
-- Rows for the fishing window and the HUD
---------------------------------------------------------------------------
local function TimedRows(rows, sub, zone, clock)
    local any = false
    for _, t in ipairs(D.timed or {}) do
        if Goals.FishedAt(t.id, sub, zone) then
            if not any then
                rows[#rows + 1] = { header = true, text = "Time-bound fish here  " .. HEX.muted .. "(server clock)|r" }
                any = true
            end
            local text = Goals.TimedText(t, clock)
            rows[#rows + 1] = { label = "", icon = Fishing.ItemIcon(t.id), text = text,
                tooltip = function(o) ns.Tooltip.Text(o, { text, t.note or "", "Source: " .. t.source }) end }
        end
    end
end

local function SpotRows(rows, mapID, spotName, skill)
    local zone = MapZone(mapID)
    local info = Goals.ZoneLevel(mapID, spotName, zone)
    rows[#rows + 1] = { header = true, text = "Zone fishing level" }
    local text, _, tip = Goals.ZoneText(info, skill)
    rows[#rows + 1] = { label = "Needs", text = text, tooltip = function(o) ns.Tooltip.Text(o, tip) end }
    -- Your own log is a supplement: it says how it went for you, not the rule.
    local spot = Fishing.GetSpot(mapID, spotName)
    if spot and skill then
        local band = Fishing.Band(skill)
        local own = spot.b[band]
        local r = Fishing.Rates(own)
        if own and r.catchPct then
            rows[#rows + 1] = { label = "Your log", text = string.format("%d%% caught at skill %d-%d", math.floor(r.catchPct * 100 + 0.5),
                band, band + Fishing.BAND - 1) .. HEX.muted .. string.format("  (%d casts)|r", r.casts) }
        else
            rows[#rows + 1] = { label = "Your log", text = HEX.dim .. "no casts here at your skill band yet|r" }
        end
    end
    TimedRows(rows, spotName, zone, Goals.ServerClock())
end

local function NowRows(rows)
    local d = db()
    local info, p = Goals.Here()
    local text, _, tip = Goals.ZoneText(info, Fishing.Effective())
    rows[#rows + 1] = { label = "Zone level", text = text, tooltip = function(o) ns.Tooltip.Text(o, tip) end }
    if d.fishExtravaganza then
        local st = Goals.Extravaganza()
        if st and (st.on or st.untilStart <= SOON) then
            rows[#rows + 1] = { label = "Contest", text = "Fishing Extravaganza " .. Goals.ExtravaganzaText(st) }
        end
    end
    local clock = Goals.ServerClock()
    for _, t in ipairs(D.timed or {}) do
        if Goals.FishedAt(t.id, p.sub, p.zone) then
            rows[#rows + 1] = { label = "", text = (Goals.TimedText(t, clock)) }
        end
    end
end

local function ZoneHUDLine()
    if not db().fishZoneHud then return nil end
    local info = Goals.Here()
    local value, warn, tip = Goals.ZoneText(info, Fishing.Effective())
    return { key = "zone", label = "Zone", value = value, warn = warn, tip = tip, icon = "Interface\\Icons\\INV_Misc_Map_01" }
end

local function ExtravaganzaHUDLine()
    if not db().fishExtravaganza then return nil end
    local st = Goals.Extravaganza()
    if not st or not (st.on or st.untilStart <= SOON) then return nil end
    return { key = "extravaganza", label = "Contest", value = "STV Extravaganza " .. Goals.ExtravaganzaText(st), warn = st.on,
        icon = "Interface\\Icons\\INV_Misc_Fish_06",
        tip = { "Stranglethorn Fishing Extravaganza", EventWhen() .. " (the vanilla schedule).",
            "First to bring 40 Speckled Tastyfish to Riggle Bassbait in Booty Bay wins.",
            "If WoW Forever runs it at all: not confirmed." } }
end

---------------------------------------------------------------------------
-- Goals view
---------------------------------------------------------------------------
local selected

local function GoalDetail(rows, g, caught, clock)
    local store = Store()
    local c = caught[g.id]
    rows[#rows + 1] = { header = true, text = g.name }
    rows[#rows + 1] = { label = "Caught", text = c and c.n > 0 and (HEX.good .. c.n .. "|r") or (HEX.muted .. "not yet|r") }
    local first = store.first[g.id]
    if first then
        rows[#rows + 1] = { label = "First", text = date("%b %d %Y", first.t) .. HEX.muted .. "  ·  " .. (first.sub or "?")
            .. ((first.zone and first.zone ~= first.sub) and (", " .. first.zone) or "") .. "  ·  skill " .. (first.skill or "?") .. "|r" }
    end
    for _, p in ipairs(c and c.places or {}) do
        rows[#rows + 1] = { label = "", text = string.format("%dx  %s", p.n, p.spot) .. HEX.muted .. "  " .. (p.map ~= p.spot and p.map or "")
            .. "  ·  skill " .. BandsText(p.bands) .. "|r" }
    end
    if c and c.unplaced then rows[#rows + 1] = { label = "", text = c.unplaced .. "x  " .. HEX.muted .. "where the game gave no map position|r" } end
    local t = timedById[g.id]
    if t then
        rows[#rows + 1] = { label = "When", text = (Goals.TimedText(t, clock)),
            tooltip = function(o) ns.Tooltip.Text(o, { t.label, t.note or "", "Source: " .. t.source }) end }
        if t.note then rows[#rows + 1] = { label = "", text = HEX.muted .. t.note .. "|r" } end
    end
    for _, q in ipairs(g.quests or {}) do
        rows[#rows + 1] = { label = "Quest", text = q.title .. HEX.muted .. string.format("  (%d)", q.count)
            .. (q.rewards and ("  ·  " .. table.concat(q.rewards, " or ")) or "") .. "|r" }
    end
    rows[#rows + 1] = { header = true, text = "Where to look  " .. HEX.muted .. "(1.12 data)|r" }
    if g.whereNote then rows[#rows + 1] = { label = "", text = g.whereNote } end
    for _, place in ipairs(g.where or {}) do
        local info = Goals.ZoneLevel(nil, place[1], place[2])
        rows[#rows + 1] = { label = "", text = place[1] .. (place[2] and (HEX.muted .. ", " .. place[2] .. "|r") or "")
            .. (info and (HEX.muted .. string.format("  ·  no get-aways from %d", info.full) .. "|r") or "") }
    end
    if not g.where and not g.whereNote then rows[#rows + 1] = { label = "", text = HEX.dim .. "?|r" } end
end

local function BuildGoals(parent)
    local v = CreateFrame("Frame", nil, parent)
    v:SetAllPoints()
    v.left = Style.Card(v, "Goals")
    v.left:SetPoint("TOPLEFT")
    v.left:SetPoint("BOTTOMLEFT")
    v.left:SetWidth(440)
    v.list = Style.List(v.left.content, { colWidths = { 50, 60 }, search = true, hint = "Search fish...", onClick = function(item)
        if item.goal then selected = item.goal UI.Refresh() end
    end })
    v.right = Style.Card(v, "")
    v.right:SetPoint("TOPLEFT", v.left, "TOPRIGHT", 10, 0)
    v.right:SetPoint("BOTTOMRIGHT")
    v.detail = Style.List(v.right.content, { labelWidth = 74 })

    function v:Footer()
        return "Caught: from your fishing log (all characters). Where to look and zone levels: vanilla 1.12 data (CMaNGOS); "
            .. "hours and seasons on the server's clock."
    end

    function v:Refresh()
        local caught = Goals.Caught()
        local clock = Goals.ServerClock()
        local rows, done, total = {}, 0, 0
        for _, group in ipairs(GROUPS) do
            rows[#rows + 1] = { header = true, text = group.label .. HEX.muted .. "  " .. group.sub .. "|r" }
            for _, g in ipairs(D.goals or {}) do
                if g.group == group.key then
                    total = total + 1
                    local c = caught[g.id]
                    local n = c and c.n or 0
                    if n > 0 then done = done + 1 end
                    local sel = selected == g.id
                    local status = ""
                    local t = timedById[g.id]
                    if t then
                        local open = Goals.TimedStatus(t, clock)
                        status = open == nil and (HEX.dim .. "?|r") or (open and (HEX.good .. t.open .. "|r") or (HEX.muted .. t.closed .. "|r"))
                    end
                    rows[#rows + 1] = {
                        goal = g.id, icon = Fishing.ItemIcon(g.id),
                        search = g.name .. " " .. group.label,
                        text = (n > 0 and (HEX.good .. "[x] |r") or (HEX.dim .. "[  ] |r")) .. (sel and HEX.accent or "") .. g.name .. (sel and "|r" or ""),
                        cols = { status, n > 0 and (HEX.good .. "x" .. n .. "|r") or (HEX.dim .. "-|r") },
                        accent = sel and COLORS.accent or nil,
                        tint = sel and { COLORS.accent[1], COLORS.accent[2], COLORS.accent[3], 0.12 } or nil,
                    }
                end
            end
        end
        self.list:SetItems(rows)
        self.left.sub:SetText(string.format("%d of %d caught  ·  click one for where and when", done, total))

        local detail = {}
        local st = Goals.Extravaganza(clock)
        self.right.title:SetText(selected and goalById[selected] and goalById[selected].name or "Stranglethorn Fishing Extravaganza")
        self.right.sub:SetText("Server time: " .. ClockText(clock))
        detail[#detail + 1] = { header = true, text = "Stranglethorn Fishing Extravaganza" }
        detail[#detail + 1] = { label = "Now", text = Goals.ExtravaganzaText(st) }
        detail[#detail + 1] = { label = "When", text = EventWhen() .. HEX.muted .. "  (vanilla, since patch 1.7)|r",
            tooltip = function(o) ns.Tooltip.Text(o, { "Source", D.extravaganza.source }) end }
        detail[#detail + 1] = { label = "", text = HEX.muted .. "40 Speckled Tastyfish to Riggle Bassbait, Booty Bay: the first one wins. "
            .. "WoW Forever may not run it.|r" }
        detail[#detail + 1] = { header = true, text = "Time and season  " .. HEX.muted .. "(server clock)|r" }
        for _, t in ipairs(D.timed or {}) do
            local text = Goals.TimedText(t, clock)
            detail[#detail + 1] = { label = "", icon = Fishing.ItemIcon(t.id), text = text,
                tooltip = function(o) ns.Tooltip.Text(o, { text, t.note or "", "Source: " .. t.source }) end }
        end
        if selected and goalById[selected] then GoalDetail(detail, goalById[selected], caught, clock) end
        self.detail:SetItems(detail)
    end
    return v
end

---------------------------------------------------------------------------
-- Settings page, slash, reminder
---------------------------------------------------------------------------
local function BuildPage(parent)
    local W = ns.Options.Widgets
    local y = -12
    y = W.Paragraph(parent, y, "What each zone's water asks of your fishing skill, fish bound to the server's hours or seasons, "
        .. "a checklist of notable catches (Nat Pagle's fish, the Stranglethorn Fishing Extravaganza, rare catches) and the "
        .. "Extravaganza's clock. Zone levels and places are vanilla 1.12 data; WoW Forever may differ.", "GameFontHighlightSmall")
    y = W.Button(parent, y, "Open the goals", 190, function() UI.Show("goals") end, "Also " .. ns.Cmd.Text("fish") .. " goals.")
    y = W.Header(parent, y, "On the fishing HUD")
    y = W.Checkbox(parent, y, "fishZoneHud", "Zone fishing level", "\"Zone: needs ~X (you Y)\": the skill from which no fish gets "
        .. "away here, marked when yours is below it.")
    y = W.Checkbox(parent, y, "fishExtravaganza", "Stranglethorn Fishing Extravaganza", "Shows the contest while it runs and in the hour "
        .. "before (Sundays 14:00-16:00 server time in vanilla; WoW Forever may not run it).")
    y = W.Checkbox(parent, y, "fishExtravaganzaChat", "Remind me in chat", "One chat line when the Extravaganza is an hour away or starts.")
    y = W.Checkbox(parent, y, "fishGoalsAnnounce", "Chat line for a first catch", "When you catch a goal fish for the first time.")
    y = W.LiveText(parent, y, 18, function()
        return "Server time: " .. ClockText(Goals.ServerClock()) .. "  ·  Extravaganza: " .. Goals.ExtravaganzaText(Goals.Extravaganza())
    end)
    return -y + 10
end

local function ZoneLine()
    local info, p = Goals.Here()
    local text = Goals.ZoneText(info, Fishing.Effective())
    return (p.sub or "?") .. ": " .. text
end

local function Slash(arg)
    if arg == "goals" then
        UI.Show("goals")
        return true
    elseif arg == "zone" then
        ns.Print("zone fishing level — " .. ZoneLine())
        return true
    end
    return false
end

local lastCheck = 0
local function Tick()
    if not db().fishExtravaganzaChat or GetTime() - lastCheck < 30 then return end
    lastCheck = GetTime()
    local st = Goals.Extravaganza()
    if not st or not (st.on or st.untilStart <= SOON) then return end
    -- The event's start, as a key: one reminder per event.
    local startsAt = time() + (st.on and -(D.extravaganza.length - st.left) or st.untilStart) * 60
    local key = date("%Y-%m-%d", startsAt)
    local store = Store()
    if store.reminded == key then return end
    store.reminded = key
    ns.Print("Stranglethorn Fishing Extravaganza " .. (st.on and ("is on: " .. Duration(st.left) .. " left") or ("starts in " .. Duration(st.untilStart)))
        .. " (vanilla schedule; WoW Forever may not run it).")
end

UI.AddView({ key = "goals", label = "Goals", build = BuildGoals })
UI.AddHUDLine(ZoneHUDLine)
UI.AddHUDLine(ExtravaganzaHUDLine)
UI.AddSpotRows(SpotRows)
UI.AddNowRows(NowRows)
Fishing.AddSlash(Slash, "goals|zone")
Fishing.On("loot", OnLoot)
table.insert(Fishing.settingsTab.pages, { label = "Goals", build = BuildPage })

ns.RegisterModule("FishingGoals", {
    defaults = {
        fishZoneHud = true,
        fishExtravaganza = true,
        fishExtravaganzaChat = false,
        fishGoalsAnnounce = true,
    },
    tick = Tick,
})
