-- Generated by tools/gen_fishing.py. Do not edit by hand: change the generator's
-- lists or re-run it (see docs/DATA.md).
-- Generated 2026-10-04 from:
--   CMaNGOS Classic DB ClassicDB_1_12_1_z2815.sql.gz (https://github.com/cmangos/classic-db):
--     skill_fishing_base_level, fishing / reference loot, items, quests;
--   wago.tools Classic Era DB2 (https://wago.tools/db2/AreaTable, /UiMapAssignment).
-- Zone level rule (cmangos/mangos-classic GameObject.cpp): hooked when skill >= base
-- and a 1-100 roll <= skill - base + 5; no fish gets away from base + 95.
local ADDON_NAME, ns = ...
-- Other fishing modules may add their own tables to ns.FishingData: keep the table.
ns.FishingData = ns.FishingData or {}
local D = ns.FishingData
D.generated = "2026-10-04"
D.zoneSource = "CMaNGOS Classic DB ClassicDB_1_12_1_z2815.sql.gz (skill_fishing_base_level)"
-- [areaID] = { name, parent zone (nil for a zone), base skill }
D.areas = {
    [1] = { "Dun Morogh", nil, -70 },
    [8] = { "Swamp of Sorrows", nil, 130 },
    [10] = { "Duskwood", nil, 55 },
    [11] = { "Wetlands", nil, 55 },
    [12] = { "Elwynn Forest", nil, -70 },
    [14] = { "Durotar", nil, -70 },
    [15] = { "Dustwallow Marsh", nil, 130 },
    [16] = { "Azshara", nil, 205 },
    [17] = { "The Barrens", nil, -20 },
    [28] = { "Western Plaguelands", nil, 205 },
    [33] = { "Stranglethorn Vale", nil, 130 },
    [36] = { "Alterac Mountains", nil, 130 },
    [38] = { "Loch Modan", nil, -20 },
    [40] = { "Westfall", nil, -20 },
    [41] = { "Deadwind Pass", nil, 330 },
    [44] = { "Redridge Mountains", nil, 55 },
    [45] = { "Arathi Highlands", nil, 130 },
    [46] = { "Burning Steppes", nil, 330 },
    [47] = { "The Hinterlands", nil, 205 },
    [85] = { "Tirisfal Glades", nil, -70 },
    [130] = { "Silverpine Forest", nil, -20 },
    [139] = { "Eastern Plaguelands", nil, 330 },
    [141] = { "Teldrassil", nil, -70 },
    [148] = { "Darkshore", nil, -20 },
    [215] = { "Mulgore", nil, -70 },
    [267] = { "Hillsbrad Foothills", nil, 55 },
    [297] = { "Jaguero Isle", "Stranglethorn Vale", 205 },
    [331] = { "Ashenvale", nil, 55 },
    [357] = { "Feralas", nil, 205 },
    [361] = { "Felwood", nil, 205 },
    [400] = { "Thousand Needles", nil, 130 },
    [405] = { "Desolace", nil, 130 },
    [406] = { "Stonetalon Mountains", nil, 55 },
    [440] = { "Tanaris", nil, 205 },
    [490] = { "Un'Goro Crater", nil, 205 },
    [493] = { "Moonglade", nil, 205 },
    [618] = { "Winterspring", nil, 330 },
    [718] = { "Wailing Caverns", nil, -20 },
    [719] = { "Blackfathom Deeps", nil, -20 },
    [796] = { "Scarlet Monastery", nil, 130 },
    [1112] = { "Jademir Lake", "Feralas", 330 },
    [1222] = { "Hetaera's Clutch", "Azshara", 330 },
    [1227] = { "Bay of Storms", "Azshara", 330 },
    [1377] = { "Silithus", nil, 330 },
    [1417] = { "Sunken Temple", nil, 205 },
    [1497] = { "Undercity", nil, -20 },
    [1519] = { "Stormwind City", nil, -20 },
    [1537] = { "Ironforge", nil, -20 },
    [1581] = { "The Deadmines", nil, -20 },
    [1637] = { "Orgrimmar", nil, -20 },
    [1638] = { "Thunder Bluff", nil, -20 },
    [1657] = { "Darnassus", nil, -20 },
    [1977] = { "Zul'Gurub", nil, 330 },
    [2017] = { "Stratholme", nil, 330 },
    [2057] = { "Scholomance", nil, 330 },
    [2100] = { "Maraudon", nil, 205 },
    [3140] = { "Scalebeard's Cave", "Azshara", 330 },
}
-- Classic UiMap ID -> areaID (outdoor zones and cities).
D.uiMapArea = { [1411] = 14, [1412] = 215, [1413] = 17, [1416] = 36, [1417] = 45, [1420] = 85, [1421] = 130, [1422] = 28, [1423] = 139, [1424] = 267, [1425] = 47, [1426] = 1, [1428] = 46, [1429] = 12, [1430] = 41, [1431] = 10, [1432] = 38, [1433] = 44, [1434] = 33, [1435] = 8, [1436] = 40, [1437] = 11, [1438] = 141, [1439] = 148, [1440] = 331, [1441] = 400, [1442] = 406, [1443] = 405, [1444] = 357, [1445] = 15, [1446] = 440, [1447] = 16, [1448] = 361, [1449] = 490, [1450] = 493, [1451] = 1377, [1452] = 618, [1453] = 1519, [1454] = 1637, [1455] = 1537, [1456] = 1638, [1457] = 1657, [1458] = 1497 }
-- Goals: id, group (pagle / stv / rare), name, quality, where = { { area, zone } },
-- whereNote, quests = { { id, title, count, rewards } }.
D.goals = {
    { id = 16967, group = "pagle", name = "Feralas Ahi", quality = 1, where = { { "Verdantis River", "Feralas" } }, quests = { { id = 6607, title = "Nat Pagle, Angler Extreme", count = 1 } } },
    { id = 16970, group = "pagle", name = "Misty Reed Mahi Mahi", quality = 1, where = { { "Misty Reed Strand", "Swamp of Sorrows" } }, quests = { { id = 6607, title = "Nat Pagle, Angler Extreme", count = 1 } } },
    { id = 16968, group = "pagle", name = "Sar'theris Striker", quality = 1, where = { { "Sar'theris Strand", "Desolace" } }, quests = { { id = 6607, title = "Nat Pagle, Angler Extreme", count = 1 } } },
    { id = 16969, group = "pagle", name = "Savage Coast Blue Sailfin", quality = 1, where = { { "Southern Savage Coast", "Stranglethorn Vale" }, { "The Savage Coast", "Stranglethorn Vale" } }, quests = { { id = 6607, title = "Nat Pagle, Angler Extreme", count = 1 } } },
    { id = 19807, group = "stv", name = "Speckled Tastyfish", quality = 1, whereNote = "Stranglethorn Vale coast during the Extravaganza (Sundays 14:00-16:00 server time)", quests = { { id = 8194, title = "Apprentice Angler", count = 5 }, { id = 8193, title = "Master Angler", count = 40, rewards = { "Arcanite Fishing Pole", "Hook of the Master Angler" } } } },
    { id = 19805, group = "stv", name = "Keefer's Angelfish", quality = 2, whereNote = "Stranglethorn Vale coast during the Extravaganza", quests = { { id = 8221, title = "Rare Fish - Keefer's Angelfish", count = 1, rewards = { "Lucky Fishing Hat" } } } },
    { id = 19806, group = "stv", name = "Dezian Queenfish", quality = 2, whereNote = "Stranglethorn Vale coast during the Extravaganza", quests = { { id = 8224, title = "Rare Fish - Dezian Queenfish", count = 1, rewards = { "High Test Eternium Fishing Line" } } } },
    { id = 19803, group = "stv", name = "Brownell's Blue Striped Racer", quality = 2, whereNote = "Stranglethorn Vale coast during the Extravaganza", quests = { { id = 8225, title = "Rare Fish - Brownell's Blue Striped Racer", count = 1, rewards = { "Nat Pagle's Extreme Anglin' Boots" } } } },
    { id = 13759, group = "rare", name = "Raw Nightfin Snapper", quality = 1, where = { { "Azshara" }, { "Burning Steppes" }, { "Eastern Plaguelands" }, { "Felwood" }, { "Jademir Lake", "Feralas" }, { "Maraudon" }, { "Moonglade" }, { "Scholomance" }, { "Silithus" }, { "Stratholme" }, { "The Hinterlands" }, { "Un'Goro Crater" }, { "Western Plaguelands" }, { "Winterspring" }, { "Zul'Gurub" } } },
    { id = 13760, group = "rare", name = "Raw Sunscale Salmon", quality = 1, where = { { "Azshara" }, { "Burning Steppes" }, { "Eastern Plaguelands" }, { "Felwood" }, { "Jademir Lake", "Feralas" }, { "Maraudon" }, { "Moonglade" }, { "Scholomance" }, { "Silithus" }, { "Stratholme" }, { "The Hinterlands" }, { "Un'Goro Crater" }, { "Western Plaguelands" }, { "Winterspring" }, { "Zul'Gurub" } } },
    { id = 13755, group = "rare", name = "Winter Squid", quality = 1, where = { { "Azshara" }, { "Bay of Storms", "Azshara" }, { "Hetaera's Clutch", "Azshara" }, { "Scalebeard's Cave", "Azshara" }, { "Feathermoon Stronghold", "Feralas" }, { "Isle of Dread", "Feralas" }, { "Ruins of Solarsal", "Feralas" }, { "Sardor Isle", "Feralas" }, { "The Forgotten Coast", "Feralas" }, { "Jaguero Isle", "Stranglethorn Vale" }, { "Tanaris" }, { "Revantusk Village", "The Hinterlands" }, { "The Overlook Cliffs", "The Hinterlands" } } },
    { id = 13756, group = "rare", name = "Raw Summer Bass", quality = 1, where = { { "Azshara" }, { "Bay of Storms", "Azshara" }, { "Hetaera's Clutch", "Azshara" }, { "Jagged Reef", "Azshara" }, { "Scalebeard's Cave", "Azshara" }, { "Southridge Beach", "Azshara" }, { "Temple of Arkkoran", "Azshara" }, { "The Ruined Reaches", "Azshara" }, { "The Shattered Strand", "Azshara" }, { "Tower of Eldara", "Azshara" }, { "Feathermoon Stronghold", "Feralas" }, { "Isle of Dread", "Feralas" }, { "Ruins of Solarsal", "Feralas" }, { "Sardor Isle", "Feralas" }, { "The Forgotten Coast", "Feralas" }, { "Jaguero Isle", "Stranglethorn Vale" }, { "Tanaris" }, { "Revantusk Village", "The Hinterlands" }, { "The Overlook Cliffs", "The Hinterlands" } } },
    { id = 13889, group = "rare", name = "Raw Whitescale Salmon", quality = 1, where = { { "Burning Steppes" }, { "Eastern Plaguelands" }, { "Jademir Lake", "Feralas" }, { "Scholomance" }, { "Silithus" }, { "Stratholme" }, { "Winterspring" }, { "Zul'Gurub" } } },
    { id = 13893, group = "rare", name = "Large Raw Mightfish", quality = 1, where = { { "Bay of Storms", "Azshara" }, { "Hetaera's Clutch", "Azshara" }, { "Scalebeard's Cave", "Azshara" } } },
    { id = 13888, group = "rare", name = "Darkclaw Lobster", quality = 1, where = { { "Bay of Storms", "Azshara" }, { "Hetaera's Clutch", "Azshara" }, { "Scalebeard's Cave", "Azshara" } } },
    { id = 13422, group = "rare", name = "Stonescale Eel", quality = 1, where = { { "Bay of Storms", "Azshara" }, { "Hetaera's Clutch", "Azshara" }, { "Jagged Reef", "Azshara" }, { "Scalebeard's Cave", "Azshara" }, { "Southridge Beach", "Azshara" }, { "Temple of Arkkoran", "Azshara" }, { "The Ruined Reaches", "Azshara" }, { "The Shattered Strand", "Azshara" }, { "Tower of Eldara", "Azshara" }, { "Tanaris" } }, quests = { { id = 9204, title = "Craftsman's Writ - Stonescale Eel", count = 40, rewards = { "Insignia of the Crusade", "Insignia of the Dawn" } } } },
    { id = 6522, group = "rare", name = "Deviate Fish", quality = 1, where = { { "Lushwater Oasis", "The Barrens" }, { "The Forgotten Pools", "The Barrens" }, { "The Stagnant Oasis", "The Barrens" }, { "Wailing Caverns" } } },
    { id = 6307, group = "rare", name = "Message in a Bottle", quality = 1, where = { { "The Zoram Strand", "Ashenvale" }, { "Darkshore" }, { "Eastern Strand", "Hillsbrad Foothills" }, { "Southshore", "Hillsbrad Foothills" }, { "Western Strand", "Hillsbrad Foothills" }, { "North Tide's Run", "Silverpine Forest" }, { "South Tide's Run", "Silverpine Forest" }, { "The Great Sea", "Silverpine Forest" }, { "The Skittering Dark", "Silverpine Forest" }, { "The Barrens" }, { "Longshore", "Westfall" }, { "Westfall Lighthouse", "Westfall" }, { "Baradin Bay", "Wetlands" }, { "Deepwater Tavern", "Wetlands" }, { "Menethil Bay", "Wetlands" }, { "Menethil Harbor", "Wetlands" }, { "The Lost Fleet", "Wetlands" } } },
    { id = 13875, group = "rare", name = "Ironbound Locked Chest", quality = 1, where = { { "Jagged Reef", "Azshara" }, { "Southridge Beach", "Azshara" }, { "Temple of Arkkoran", "Azshara" }, { "The Ruined Reaches", "Azshara" }, { "The Shattered Strand", "Azshara" }, { "Tower of Eldara", "Azshara" }, { "Tanaris" } } },
    { id = 13918, group = "rare", name = "Reinforced Locked Chest", quality = 1, where = { { "Bay of Storms", "Azshara" }, { "Hetaera's Clutch", "Azshara" }, { "Scalebeard's Cave", "Azshara" } } },
}
D.whereSource = "https://warcraft.wiki.gg/wiki/Stranglethorn_Fishing_Extravaganza"
-- Server hours [from, to) / seasons [from, to] as month * 100 + day; sources inline.
D.timed = {
    { id = 13759, hours = { 18, 6 }, best = { 0, 6 }, label = "night only", open = "night", closed = "day", note = "Also caught any time inside the Sunken Temple.", source = "https://warcraft.wiki.gg/wiki/Raw_Nightfin_Snapper (\"only between 6 PM and 6 AM\", best 12-6 AM)" },
    { id = 13760, hours = { 6, 24 }, best = { 12, 18 }, label = "day and evening", open = "yes", closed = "night", source = "https://blizzardwatch.com/2019/10/02/make-gold-fishing-wow-classic/ (none 12-6 AM, best 12-6 PM)" },
    { id = 13755, season = { 923, 319 }, best = { 12, 18 }, label = "winter (Sep 23 - Mar 19)", open = "in season", closed = "out of season", source = "https://warcraft.wiki.gg/wiki/Winter_Squid (from Sep 23, best 12:00-18:00 server time); end date: CMaNGOS game_event 35 'Winter Season Fishing' (Sep 23 01:00 + 178 days)" },
    { id = 13756, season = { 321, 923 }, label = "summer (Mar 21 - Sep 23)", open = "in season", closed = "out of season", source = "CMaNGOS game_event 36 'Summer Season Fishing' (Mar 21 01:00 + 187 days); https://warcraft.wiki.gg/wiki/Raw_Summer_Bass (\"during the summer\")" },
}
D.extravaganza = { weekday = 1, start = 840, length = 120, source = "https://warcraft.wiki.gg/wiki/Stranglethorn_Fishing_Extravaganza (patch 1.7.0: Sundays 2:00 - 4:00 PM server time; 40 Speckled Tastyfish to Riggle Bassbait, Booty Bay)" }
